"""Script-of-scripts: the self-modifying core.

Given a resolved composition (from lib.compose.resolve), emit a faithful,
standalone, one-shot Python script that reproduces it deterministically, then
run it. The emitted script is a first-class artifact: readable, editable,
re-runnable, and importable — it may itself import lib.effects and may itself
emit more scripts. This is the "glorified agentic environment plugin" part:
the program writes programs.

`generate()` = resolve() + emit_script() + run_script().
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from . import OUT_DIR, ROOT
from . import effects


def _fn_name(filter_name: str) -> str | None:
    fn = effects.EFFECTS.get(filter_name)
    return fn.__name__ if fn else None


def _filtered_kwargs(fn_name: str, params: dict) -> dict:
    fn = getattr(effects, fn_name, None)
    if not fn:
        return {}
    return effects.filter_kwargs(fn, params)


def _py(s: str) -> str:
    return json.dumps(s)


def emit_script(resolved: dict, out_dir: Path | None = None, name: str | None = None) -> Path:
    """Write a standalone one-shot script reproducing the resolved composition."""
    out_dir = out_dir or OUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    name = name or resolved["style_id"]
    script_path = out_dir / f"compose_{name}.py"

    w, h = resolved["canvas"]
    lines: list[str] = []
    A = lines.append

    A("#!/usr/bin/env python3")
    A(f"\"\"\"{resolved['style_id']} still — deterministic one-shot (seed={resolved['seed']}).")
    A("")
    A("Auto-generated by amtech-computer-use-graphics `generate`. Edit freely; re-run to reproduce.")
    A("This script is the artifact: it imports lib.effects and can emit more scripts.")
    A("\"\"\"")
    A("import sys")
    A("from pathlib import Path")
    A(f"sys.path.insert(0, {_py(str(ROOT))})")
    A("from PIL import Image, ImageDraw")
    A("from lib import effects")
    A("")
    A("")
    A("def main():")
    A(f"    W, H = {w}, {h}")
    A(f"    im = Image.new('RGB', (W, H), {_py(resolved['background'])})")
    A("")

    # photo
    if resolved.get("source"):
        A(f"    im = effects.cover_crop(Image.open({_py(resolved['source'])}).convert('RGB'), W, H)")
        A("")

    # pillow ops
    for op, val in resolved.get("pillow", {}).items():
        if op == "contrast" and val:
            A(f"    im = effects.contrast(im, factor={float(val)})")
        elif op == "color" and val:
            A(f"    im = effects.saturation(im, factor={float(val)})")
        elif op == "bottom_lift" and val:
            start = float(resolved["pillow"].get("lift_start", 0.45))
            strength = float(resolved["pillow"].get("lift_strength", 0.35))
            lift_color = resolved["pillow"].get("lift_color")
            if lift_color:
                A(f"    im = effects.bottom_lift(im, start={start}, strength={strength}, "
                  f"color=effects.hex_rgb({_py(str(lift_color))}))")
            else:
                A(f"    im = effects.bottom_lift(im, start={start}, strength={strength})")
    if resolved.get("pillow"):
        A("")

    # circle inset sticker (photo2)
    ci = resolved.get("pillow", {}).get("circle_inset")
    if ci and resolved.get("photo2"):
        d = float(ci.get("d", 0.28))
        ring = int(ci.get("ring", 12))
        rcol = ci.get("ring_color", "#ff2bd6")
        cx = float(ci.get("cx", 0.80))
        cy = float(ci.get("cy", 0.18))
        A(f"    _sticker = effects.circle_sticker(Image.open({_py(resolved['photo2'])}).convert('RGB'), "
          f"int(min(W, H) * {d}), {ring}, {_py(rcol)})")
        A(f"    im.paste(_sticker, (int(W * {cx}) - _sticker.size[0] // 2, "
          f"int(H * {cy}) - _sticker.size[1] // 2), _sticker)")
        A("")

    # filters
    for f in resolved.get("filters", []):
        fn = _fn_name(f["name"])
        if not fn:
            A(f"    # filter not mapped: {f['name']} {f.get('param', {})}")
            continue
        kwargs = _filtered_kwargs(fn, f.get("param", {}))
        args = ", ".join(f"{k}={v!r}" for k, v in kwargs.items())
        A(f"    im = effects.{fn}(im{', ' + args if args else ''})")
    if resolved.get("filters"):
        A("")

    # masthead banner (real brand asset pasted top-left); record its height so
    # the corner badge can bottom-align to it.
    mb = resolved.get("pillow", {}).get("masthead_banner")
    if mb:
        asset = resolved.get("pillow", {}).get("masthead_banner_asset", "lime")
        banner_path = ROOT / "assets" / "banners" / f"banner-{asset}.png"
        width_frac = float(mb.get("width", 0.46))
        A(f"    im, _banner_h = effects.masthead_banner(im, {_py(str(banner_path))}, "
          f"width_frac={width_frac})")
        A("")

    # corner logo badge (brand asset)
    badge = resolved.get("pillow", {}).get("logo_badge")
    if badge:
        asset = badge.get("asset", "worldmap")
        corner = badge.get("corner", "top_right")
        size = float(badge.get("size", 0.10))
        margin = float(badge.get("margin", 0.03))
        bottom = badge.get("bottom")
        logo_path = ROOT / "assets" / "logos" / f"logo-{asset}.png"
        if bottom == "banner":
            A(f"    im = effects.corner_badge(im, {_py(str(logo_path))}, "
              f"corner={_py(corner)}, size={size}, margin={margin}, bottom=_banner_h)")
        else:
            A(f"    im = effects.corner_badge(im, {_py(str(logo_path))}, "
              f"corner={_py(corner)}, size={size}, margin={margin}, "
              f"bottom={bottom!r})")
        A("")

    # draw
    A("    draw = ImageDraw.Draw(im)")
    for r in resolved.get("rects", []):
        A(f"    draw.rectangle([{r['x1']}, {r['y1']}, {r['x2']}, {r['y2']}], "
          f"fill={_py(r['fill'])})")
    for t in resolved.get("texts", []):
        if t.get("type") == "stack":
            font_path = t.get("font") or resolved["font"]
            stack_literal = "[\n"
            for ln in t.get("lines", []):
                stack_literal += (f"        ({_py(ln['text'])}, {_py(ln['color'])}, "
                                  f"{int(ln['size'])}),\n")
            stack_literal += "    ]"
            A(f"    effects.stack_lines(draw, {stack_literal}, {t['cx']}, {t['y0']}, "
              f"{t['max_w']}, {t['bottom']}, stroke={t.get('stroke', 7)}, "
              f"gap={t.get('gap')!r}, fill={t.get('fill', False)}, "
              f"spec={_py(font_path)})")
            continue
        font_path = t.get("font") or resolved["font"]
        anchor = t.get("anchor", "la")
        stroke = int(t.get("stroke", 6))
        A(f"    effects.stroke_text(draw, ({t['x']}, {t['y']}), {_py(t['text'])}, "
          f"effects.font({_py(font_path)}, {t['size']}), {_py(t['color'])}, "
          f"width={stroke}, anchor={_py(anchor)})")
    A("")

    out_png = out_dir / f"{name}.png"
    A(f"    out = Path({_py(str(out_png))})")
    A("    out.parent.mkdir(parents=True, exist_ok=True)")
    A("    im.convert('RGB').save(out, 'PNG')")
    A(f"    print(out)")
    A("")
    A("")
    A('if __name__ == "__main__":')
    A("    main()")

    script_path.write_text("\n".join(lines) + "\n")
    return script_path


def run_script(script_path: Path) -> dict:
    proc = subprocess.run([sys.executable, str(script_path)],
                          capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr or proc.stdout)
        raise SystemExit(f"generated script failed (exit {proc.returncode}): {script_path}")
    return {"script": str(script_path), "output": proc.stdout.strip(),
            "returncode": proc.returncode}


def generate(
    style_id: str,
    brand_id: str | None = None,
    source: str | None = None,
    photo2: str | None = None,
    copy_overrides: dict | None = None,
    font_override: str | None = None,
    seed: int | None = None,
    out_dir: Path | None = None,
) -> dict:
    """Resolve -> emit -> run. Returns script path + stdout."""
    from .compose import resolve
    from .source import resolve as resolve_source
    out_dir = out_dir or OUT_DIR
    resolved = resolve(style_id, brand_id, source, photo2, copy_overrides,
                       font_override, seed)
    if resolved.get("source"):
        resolved["source"] = str(resolve_source(resolved["source"]))
    if resolved.get("photo2"):
        resolved["photo2"] = str(resolve_source(resolved["photo2"]))
    script = emit_script(resolved, out_dir)
    result = run_script(script)
    result["resolved"] = resolved
    result["png"] = str(out_dir / f"{style_id}.png")
    return result
